### ISSUE TITLE
poetry install error

### ISSUE THREAD

**Issue by yangboz** [artefactory/streamlit_prophet#21]
## 🔬 How To Reproduce

1. ...

### Environment

* OS: macOS
* Python version, 3.8

```bash
python --version
```

### Screenshots

at ~/miniconda3/lib/python3.8/site-packages/poetry/installation/executor.py:627 in _download_link
      623│                     )
      624│                 )
      625│ 
      626│             if archive_hashes.isdisjoint(hashes):
    → 627│                 raise RuntimeError(
      628│                     "Invalid hashes ({}) for {} using archive {}. Expected one of {}.".format(
      629│                         ", ".join(sorted(archive_hashes)),
      630│                         package,
      631│                         archive_path.name,
![Screenshot 2022-05-27 at 11 08 40 AM](https://user-images.githubusercontent.com/481954/170621256-2fde1f90-38cf-4ff5-88a8-af4eab865e2b.png)

## 📈 Expected behavior

it works as README showed.

## 📎 Additional context

maybe related to #20 

finally it works after a clean conda created py38, then poetry install  all successed.  the cmd under project root is

```
poetry run streamlit run streamlit_prophet/app/dashboard.py

```
 hope it helps others.
![image](https://user-images.githubusercontent.com/481954/170926113-9cf731b5-1baa-48a7-8da8-4d7ddcb7fb9c.png)

**Comment by MaximeLutel** [comment]
Hello @yangboz, thanks for sharing!

**Comment by yangboz** [comment]
> Hello @yangboz, thanks for sharing!

my pleasure. :)
