### ISSUE TITLE
Can not build docker container

### ISSUE THREAD

**Issue by maurice1979** [artefactory/streamlit_prophet#25]
## 🐛 Bug Report

I could not create the docker container with the current Dockerfile. I got an error when creating the docker container with command:

```bash
make docker
```

## 🔬 How To Reproduce

1. Clone the repository
2. Type `make docker`

### Environment

* OS: macOS
* Python version: Python 3.9.12

### Screenshots

The error is related to a poetry parameter that is no longer used:
```
The `--no-dev` option is deprecated, use the `--only main` notation instead. 
```
<img width="1391" alt="imagen" src="https://user-images.githubusercontent.com/7785214/199413296-02104e90-48df-42d4-b137-7f2121eedd90.png">

## 📈 Expected behavior

The container is built and I can play with it! :-) 

## 📎 Additional context

Tried to update the Dockerfile and use `--only main` notation instead of `--no-dev`. Then another error message appears:
```bash
Because streamlit-prophet depends on pip (^21.3.1) which doesn't match any versions, version solving failed.
```
<img width="1387" alt="imagen" src="https://user-images.githubusercontent.com/7785214/199414771-c313b925-4cf0-4595-aace-5d22d4208013.png">

**Comment by MaximeLutel** [comment]
Hi @maurice1979, I have update the requirements, it should be good now.
