### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit_prophet'

### ISSUE THREAD

**Issue by Eunice-Wyy** [artefactory/streamlit_prophet#34]
## 🐛 Bug Report

Unable to run streamlit app as "No module named 'streamlit_prophet'"

## 🔬 How To Reproduce

1. Git clone the repo
2. Error when downloading command "pip install -U streamlit_prophet"

### Environment

* OS: Windows 
* Python version, get it with: 3.7.16

### Screenshots

1. When downloading:

![Screenshot 2024-05-15 100403](https://github.com/artefactory/streamlit_prophet/assets/144644083/70a4b7f4-6a12-4094-b5a3-10c2aee0e6aa)

![image](https://github.com/artefactory/streamlit_prophet/assets/144644083/77c26be8-b625-4cd5-a19d-191ae1b94492)

**Comment by TomDarmon** [comment]
It looks like the pypi package is outdated, as an alternative you could build it from source with the following steps:

```bash
git clone git@github.com:artefactory/streamlit_prophet.git
cd streamlit_prophet
# Install poetry, optional if you already have it 
# curl -sSL https://raw.githubusercontent.com/python-poetry/install.python-poetry.org/main/install-poetry.py | POETRY_HOME=/home/docker_user/poetry python
poetry install
poetry run streamlit_prophet deploy dashboard
```
